services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yourproject
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - your_project_net

  api:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - secrets/prod.env 
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/yourproject
    volumes:
      - ./app:/app
    networks:
      - your_project_net

volumes:
  db:
    driver: local

networks:
  your_project_net:
    external: true
